#ifndef RENDERER_H
#define RENDERER_H

#include <GL/glew.h>
#include <GLFW/glfw3.h>
#include <vector>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>

#include "shader.h"
#include "house.h"
#include "camera.h"

const int WIDTH = 1920;
const int HEIGHT = 1080;

class Renderer{
    glm::mat4 mat_projection;
    Shader shader;

    public:
        GLFWwindow* window;
        Camera camera;
        float height_clip;
        
        Renderer(){};
        Renderer(float x, float y, float z, float fov);

        // sets uniform variables for each of the houses to be generated by the geometry shader and draws them.
        void render(std::vector<House> &houses);

        void terminate();
};
#endif
